[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "LucydDemon"
name = "DownedAwareness"
description = "Cant see where your unconscious friends are? This mod adds an indicator to make it easier to find them."
websiteUrl = "https://github.com/lucyd-dev/DownedAwareness/"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2403"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../Packages"

[[build.copy]]
source = "./artifacts/bin/DownedAwareness/release/lucyddemon.downedawareness.dll"
target = "BepInEx/plugins/DownedAwareness/lucyddemon.downedawareness.dll"

[[build.copy]]
source = "./LICENSE"
target = "LICENSE"

[[build.copy]]
source = "./CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = [ "peak" ]
[publish.categories]
peak = [ "mods", "qol", "client", "misc" ]
